Introduce VerifyTokenHash to support the PKCE flow for email signup
supabase-community/gotrue-csharp pull request #98
Opened 2024-06-27 15:59 UTC by alexbakker

Relevant documentation:
https://supabase.com/docs/guides/auth/passwords?queryGroups=flow&flow=pkce#signing-up-with-an-email-and-password

2024-06-28 10:30 UTC, acupofjose requested changes
Awesome work, thank you! Just minor change and we should be good to go.

2024-06-28 10:30 UTC, acupofjose commented on Gotrue/Interfaces/IGotrueApi.cs
This should be changed to the generic `TSession`

2024-06-28 11:11 UTC, alexbakker commented
Fixed!

2024-06-28 11:43 UTC, merged

2024-06-28 11:44 UTC, acupofjose commented
LGTM! I’ll add it to the next release

2024-06-29 12:21 UTC, acupofjose commented
Available in 5.0.6 and will be included shortly in the next Supabase minor version